##
# A basic Ubuntu "Jammy Jellyfish" build environment.

FROM ubuntu:22.04 AS base
ENV DEBIAN_FRONTEND noninteractive
ENV BUNDLE_SILENCE_ROOT_WARNING true

RUN apt-get update && \
    apt-get install -y wget build-essential ninja-build python3 zlib1g-dev

ADD ./build-cmake.sh .
RUN ./build-cmake.sh

FROM base AS ruby
ENV PATH=/opt/ruby/bin:$PATH
ADD ./build-ruby.sh .
RUN ./build-ruby.sh

FROM base AS llvm
ADD ./build-llvm.sh .
RUN ./build-llvm.sh

FROM base AS build
ENV PATH=/opt/ruby/bin:$PATH

COPY --from=ruby /opt/ruby /opt/ruby
COPY --from=llvm /opt/llvm /opt/llvm

ENV LLVM_ROOT=/opt/llvm

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y valgrind git clang zip gcovr pkg-config automake clang autopoint gettext libtool gperf xvfb libgtk-3-dev libpcre2-dev libxrandr-dev libxinerama-dev libxcursor-dev libxxf86vm-dev libglu1-mesa-dev libyaml-0-2 libfontconfig1-dev libwebkit2gtk-4.0-dev libopenal-dev
