##
# A basic devkitPro environment for compiling to Nintendo Switch.

FROM devkitpro/devkita64:20231108 AS devkitpro

FROM ghcr.io/blitz3d-ng/env:debian-12 AS build
ENV DEVKITPRO=/opt/devkitpro

COPY --from=devkitpro /opt/devkitpro /opt/devkitpro
