##
# A basic mingw + wine build environment.

FROM ghcr.io/blitz3d-ng/env:debian-11 AS build

RUN dpkg --add-architecture i386 && \
    apt-get update && apt-get upgrade -y && \
    apt-get install -y mingw-w64-i686-dev g++-mingw-w64-i686-win32 wine32 wine64
