##
# A basic Ubuntu "Hirsute Hippo" build environment.

FROM ubuntu:21.04 AS base
ENV DEBIAN_FRONTEND noninteractive
ENV BUNDLE_SILENCE_ROOT_WARNING true

RUN apt-get update && \
    apt-get install -y wget build-essential ninja-build python3

# cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.21.2/cmake-3.21.2-linux-x86_64.sh && \
    bash cmake-3.21.2-linux-x86_64.sh --skip-license --prefix=/usr/local && \
    rm cmake-3.21.2-linux-x86_64.sh

FROM base AS ruby
ENV PATH=/opt/ruby/bin:$PATH
ADD ./build-ruby.sh .
RUN ./build-ruby.sh

FROM base AS llvm
ADD ./build-llvm.sh .
RUN ./build-llvm.sh

FROM base AS build
ENV PATH=/opt/ruby/bin:$PATH

COPY --from=ruby /opt/ruby /opt/ruby
COPY --from=llvm /opt/llvm /opt/llvm

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y git clang zip pkg-config automake zlib1g-dev clang libgtk-3-dev libpcre2-dev libxrandr-dev libxinerama-dev libxcursor-dev uuid-dev libfontconfig1-dev libglu1-mesa-dev libyaml-0-2
