# LLVM config customize for our needs.

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_BUILD_TYPE Release)

set(LLVM_ENABLE_PROJECTS  "lld" CACHE STRING "" FORCE)
set(LLVM_ENABLE_RUNTIMES  "" CACHE STRING "" FORCE)
set(LLVM_BUILD_TOOLS OFF CACHE STRING "" FORCE)
set(LLVM_TARGETS_TO_BUILD "AArch64;ARM;WebAssembly;X86" CACHE STRING "" FORCE)
set(LLVM_HAVE_LIBXAR OFF CACHE STRING "" FORCE)
set(LLVM_USE_CRT_RELEASE MT CACHE STRING "" FORCE)
