name: CI

on:
  push:
    branches:
      - master

jobs:
  specs:
    name: ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - debian-10
          - debian-11
          - android
          - nx
    steps:
      - name: Setup docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.${{ matrix.platform }}
          tags: ghcr.io/blitz3d-ng/env:${{ matrix.platform }}
          push: true
