name: CI

on:
  push:
#     branches:
#       - master

jobs:
  llvm_win64:
    name: LLVM (win64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: win64
      - uses: seanmiddleditch/gha-setup-ninja@master
      - shell: pwsh
        run: .\build-llvm.ps1
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: llvm-win64
          path: llvm/
  # distros:
  #   name: ${{ matrix.platform }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       platform:
  #         - debian-10
  #         - debian-11
  #         - ubuntu-21.04
  #         - ubuntu-22.04
  #   steps:
  #     - name: Setup docker
  #       uses: docker/setup-buildx-action@v1
  #
  #     - name: Log in to the GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #
  #     - name: Build image
  #       uses: docker/build-push-action@v2
  #       with:
  #         file: Dockerfile.${{ matrix.platform }}
  #         tags: ghcr.io/blitz3d-ng/env:${{ matrix.platform }}
  #         pull: true
  #         push: true
  #
  # sdks:
  #   needs: [distros]
  #   name: ${{ matrix.platform }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       platform:
  #         - android
  #         - nx
  #         - mingw
  #         - emscripten
  #   steps:
  #     - name: Setup docker
  #       uses: docker/setup-buildx-action@v1
  #
  #     - name: Log in to the GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #
  #     - name: Build image
  #       uses: docker/build-push-action@v2
  #       with:
  #         file: Dockerfile.${{ matrix.platform }}
  #         tags: ghcr.io/blitz3d-ng/env:${{ matrix.platform }}
  #         pull: true
  #         push: true
