name: CI

on: [push]

jobs:
  distros:
    name: ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - debian-10
          - debian-11
          - debian-12
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          - archlinux
    steps:
      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.${{ matrix.platform }}
          tags: |
            ghcr.io/blitz3d-ng/env:${{ matrix.platform }}-${{ github.ref_name }}
            ghcr.io/blitz3d-ng/env:${{ matrix.platform }}-run${{ github.run_number }}
          pull: true
          push: true

  sdks:
    needs: [distros]
    name: ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - android
          - nx
          - mingw
          - emscripten
    steps:
      - name: Setup docker
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker pull ghcr.io/blitz3d-ng/env:debian-12-run${{ github.run_number }}
          docker tag ghcr.io/blitz3d-ng/env:debian-12-run${{ github.run_number }} ghcr.io/blitz3d-ng/env:debian-12

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.${{ matrix.platform }}
          tags: ghcr.io/blitz3d-ng/env:${{ matrix.platform }}-${{ github.ref_name }}
          pull: false
          push: true
